version: '3.8'

services:
  chatix-app:
    image: openjdk:17-jdk
    container_name: chatix-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "50000:8080"
    networks:
      - chatix-network
    depends_on:
      - chatix-db

  check-mysql-started:
    image: jwilder/dockerize:0.6.1
    depends_on:
      - chatix-db
    command: 'dockerize -wait=tcp://chatix-db:3306'

  chatix-db:
    image: mysql:8.0
    container_name: chatix-db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - chatix-data:/var/lib/mysql
    networks:
      - chatix-network

volumes:
  chatix-data:

networks:
  chatix-network: